// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JalaaliJs from "jalaali-js";

function utcMillisToLocalDate(millis) {
  return JalaaliJs.toJalaali(new Date(millis));
}

function toYYYYMMDD(param) {
  return String(param.jy) + ("/" + (String(param.jm) + ("/" + String(param.jd))));
}

function utcMillisToYYYYMMDD(millis) {
  return toYYYYMMDD(JalaaliJs.toJalaali(new Date(millis)));
}

export {
  utcMillisToLocalDate ,
  toYYYYMMDD ,
  utcMillisToYYYYMMDD ,
}
/* jalaali-js Not a pure module */
